name: Download Winget Manifests

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  fetch-manifests:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Specify the Python version

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml

    - name: Run Script to Fetch Winget Manifests
      run: |
        python script.py

    - name: Commit and Push Changes
      if: success()
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add manifests
        git commit -m "Update latest manifests"
        git push
