name: Download Winget Manifests

on:
  workflow_dispatch: # Allows manual trigger
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  fetch-manifests:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Git identity
        run: |
          git config --global user.email "dawnzac88@gmail.com"
          git config --global user.name "Dawn Zac"

      - name: Set up Git credentials
        run: |
          git remote set-url origin https://github-actions:$(echo ${{ secrets.GH_TOKEN }})@github.com/Dawnzac/patch-node.git

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10" # Specify the Python version

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyyaml beautifulsoup4

      - name: Run Script to Fetch Winget Manifests
        run: |
          python download_manifest7.py

      - name: Commit and Push Changes
        if: success()
        run: |
          git add manifests
          git commit -m "Update latest manifests"
          git push origin main
