name: Manual workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: "App name"
        default: "World"
        required: true
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Send greeting
        run: echo "Hello ${{ inputs.name }}"
